watchdog improvements

diff --git a/rootfs/etc/services.d/feeder-watchdog/run b/rootfs/etc/services.d/feeder-watchdog/run
--- a/rootfs/etc/services.d/feeder-watchdog/run
+++ b/rootfs/etc/services.d/feeder-watchdog/run
@@ -33,7 +33,7 @@ fix_feeder ()
   sleep 15
 
   # check if data is flowing again:
-  [[ "$(grep captured <<< $(timeout --preserve-status 3 tcpdump -i wg0 udp port ${DEST_PORT} 2>/dev/stdout 1>/dev/null) | awk '{print $1}')" == "0" ]] && return 0 || return 1 
+  [[ "$(grep captured <<< $(timeout --preserve-status 3 tcpdump -i wg0 udp port ${DEST_PORT} 2>/dev/stdout 1>/dev/null) | awk '{print $1}')" == "0" ]] && return 0 || return 1
 }
 
 [[ -z "$WATCHDOG_MAX_FAILURES" ]] && WATCHDOG_MAX_FAILURES=10 || true
@@ -49,21 +49,21 @@ do
       (( PING_FAILURE_COUNT++ )) || true
       if (( PING_FAILURE_COUNT > WATCHDOG_MAX_FAILURES ))
       then
-        echo "[$APPNAME][$(date)] Cannot reach ${DEST_HOST} -- Maximum Failure Count of ${WATCHDOG_MAX_FAILURES} exceeded."
-        echo "[$APPNAME][$(date)] Trying to fix the VPN connection..."
+        echo "[$APPNAME][$(date)] Ping Failure: cannot reach ${DEST_HOST} -- Maximum Failure Count of ${WATCHDOG_MAX_FAILURES} exceeded." | tee -a /var/log/feeder-watchdog.log
+        echo "[$APPNAME][$(date)] Ping Failure: Trying to fix the VPN connection..." | tee -a /var/log/feeder-watchdog.log
         if ! fix_wg ${DEST_HOST}
         then
-          echo "[$APPNAME][$(date)] VPN fix attempt failed. Shutting down the container to auto-restart..."
+          echo "[$APPNAME][$(date)] Ping Failure: VPN fix attempt failed. Shutting down the container to auto-restart..." | tee -a /var/log/feeder-watchdog.log
           s6-svscanctl -t /var/run/s6/services
         else
-          echo "[$APPNAME][$(date)] VPN fix attenpt succeeded!"
+          echo "[$APPNAME][$(date)] Ping Failure: VPN fix attempt succeeded!" | tee -a /var/log/feeder-watchdog.log
           PING_FAILURE_COUNT=0
         fi
       else
-        echo "[$APPNAME][$(date)] Cannot reach ${DEST_HOST} -- Failure ${PING_FAILURE_COUNT} of max. ${WATCHDOG_MAX_FAILURES} allowed failures."
+        echo "[$APPNAME][$(date)] Ping Failure: cannot reach ${DEST_HOST} -- Failure ${PING_FAILURE_COUNT} of max. ${WATCHDOG_MAX_FAILURES}." | tee -a /var/log/feeder-watchdog.log
       fi
     else
-      (( PING_FAILURE_COUNT > 0 )) && echo "[$APPNAME][$(date)] ${DEST_HOST} can be reached again." || true
+      (( PING_FAILURE_COUNT > 0 )) && echo "[$APPNAME][$(date)] Ping Failure: ${DEST_HOST} can be reached again."  | tee -a /var/log/feeder-watchdog.log || true
       PING_FAILURE_COUNT=0
     fi
 
@@ -73,22 +73,21 @@ do
       (( TCPD_FAILURE_COUNT++ )) || true
       if (( TCPD_FAILURE_COUNT > WATCHDOG_MAX_FAILURES ))
       then
-        echo "[$APPNAME][$(date)] No data is flowing to UDP port ${DEST_PORT}-- Maximum Failure Count of ${WATCHDOG_MAX_FAILURES} exceeded."
-        echo "[$APPNAME][$(date)] Performing last-ditch effort to restart the feeder..."
+        echo "[$APPNAME][$(date)] DataFlow Failure: No data is flowing to UDP port ${DEST_PORT}-- Maximum Failure Count of ${WATCHDOG_MAX_FAILURES} exceeded." | tee -a /var/log/feeder-watchdog.log
+        echo "[$APPNAME][$(date)] DataFlow Failure: Performing last-ditch effort to restart the feeder..." | tee -a /var/log/feeder-watchdog.log
         if ! fix_feeder
         then
-          echo "[$APPNAME][$(date)] Last-ditch effort failed. Shutting down the container to auto-restart..."
+          echo "[$APPNAME][$(date)] DataFlow Failure: Last-ditch effort failed. Shutting down the container to auto-restart..." | tee -a /var/log/feeder-watchdog.log
           s6-svscanctl -t /var/run/s6/services
         else
-          echo "[$APPNAME][$(date)] Last-ditch effort succeeded. Data is f flowing again!"
+          echo "[$APPNAME][$(date)] DataFlow Failure: Last-ditch effort succeeded. Data is f flowing again!" | tee -a /var/log/feeder-watchdog.log
           TCPD_FAILURE_COUNT=0
-       fi  
+       fi
       else
-        echo "[$APPNAME][$(date)] No data is flowing to UDP port ${DEST_PORT} -- Failure count ${TCPD_FAILURE_COUNT} of max. ${WATCHDOG_MAX_FAILURES} allowed failures."
+        echo "[$APPNAME][$(date)] DataFlow Failure: No data is flowing to UDP port ${DEST_PORT} -- Failure count ${TCPD_FAILURE_COUNT} of max. ${WATCHDOG_MAX_FAILURES} allowed failures." | tee -a /var/log/feeder-watchdog.log
       fi
     else
-      (( TCPD_FAILURE_COUNT > 0 )) && echo "[$APPNAME][$(date)] Data is flowing again to UDP port ${DEST_PORT}." || true
-
+      (( TCPD_FAILURE_COUNT > 0 )) && echo "[$APPNAME][$(date)] DataFlow Failure: Data is flowing again to UDP port ${DEST_PORT}."  | tee -a /var/log/feeder-watchdog.log || true
       TCPD_FAILURE_COUNT=0
     fi
 
@@ -96,5 +95,11 @@ do
     PING_FAILURE_COUNT=0
     TCPD_FAILURE_COUNT=0
   fi
+
+  # limit the logs to max 1000 lines:
+  tail -n 1000 /var/log/feeder-watchdog.log > /tmp/wdlog.tmp
+  mv /tmp/wdlog.tmp /var/log/feeder-watchdog.log
+
+  # sleep a bit before we repeat the whole thing again:
   sleep 10
 done
