implemented loop-through NTP servers

diff --git a/rootfs/etc/services.d/clockdiff-service/run b/rootfs/etc/services.d/clockdiff-service/run
--- a/rootfs/etc/services.d/clockdiff-service/run
+++ b/rootfs/etc/services.d/clockdiff-service/run
@@ -15,10 +15,13 @@ exec 2>&1
 
 APPNAME="$(hostname)/clockdiff-service"
 
-[[ -z "$NTP_REFSERVER" ]] && NTP_REFSERVER="pool.ntp.org" || true
+[[ -z "$NTP_REFSERVER" ]] && NTP_REFSERVER="pool.ntp.org,ntp1.hetzner.de,ntp2.hetzner.de,ntp3.hetzner.de,time.google.com,time.windows.com,ptbtime1.ptb.de,ptbtime2.ptb.de,ptbtime3.ptb.de" || true
 SLEEPTIME="60s"
 RUNFILE="/run/clockdiff.status"
 
+# parse NTP_REFSERVER array:
+readarray -d "," -t ntparray <<< "$NTP_REFSERVER"
+ntpindex=0
 
 [[ -n "$VERBOSELOGS" ]] && VERBOSELOGS="${VERBOSELOGS,,}" || true
 if [[ "$VERBOSELOGS" == "true" ]] || [[ "$VERBOSELOGS" == "on" ]] || [[ "$VERBOSELOGS" == "enabled" ]]
@@ -33,23 +36,20 @@ fi
 if [[ -n "$VERBOSELOGS" ]]
 then
     LOGINTERVAL=600
-    MAX_ERROR_COUNT=5
 else
     LOGINTERVAL=3600
-    MAX_ERROR_COUNT=10
 fi
 
 lastlog=$(($(date +%s) - LOGINTERVAL - 1))
-errorcount=5
 
 echo "$(date +%s)000,99999,99999,\"clockdiff not yet available\"" > "${RUNFILE}"
 
 while true
 do
     lastchecked="$(date +%s)000"
-    timediff="$(clockdiff $NTP_REFSERVER 2>&1)"
+    timediff="$(clockdiff "${ntparray[$ntpindex]}" 2>&1)"
 
-    # capture a few errors
+    # capture a few fatal errors
     if grep -i "command not found" <<< "${timediff}" >/dev/null 2>&1
     then
         echo "${lastchecked},99999,99999,\"clockdiff cmd not installed\"" > "${RUNFILE}"
@@ -62,48 +62,38 @@ do
         echo "[$(date)][$APPNAME] FATAL: topped clockdiff-server: NICE capability not available in container"
         sleep infinity
     fi
+
+    # capture a few temporary errors; generally we'll cycle to the next NTP_REFSERVER and try again:
     if grep -i "Name or service not known" <<< "${timediff}" >/dev/null 2>&1
     then
-        echo "${lastchecked},99999,99999,\"Cannot resolve NTP server ${NTP_REFSERVER}\"" > "${RUNFILE}"
-        (( errorcount++ ))
-        if (( errorcount > MAX_ERROR_COUNT )) && [[ -n "$VERBOSELOGS" ]]
-        then
-            echo "[$(date)][$APPNAME] WARNING: Temporary issue resolving NTP server ${NTP_REFSERVER}"
-            errorcount=0
-        fi
-        sleep $SLEEPTIME
+        echo "${lastchecked},99999,99999,\"Cannot resolve NTP server ${ntparray[$ntpindex]}\"" > "${RUNFILE}"
+        echo "[$(date)][$APPNAME] WARNING: Temporary issue resolving NTP server ${ntparray[$ntpindex]}; cycling to next NTP server"
+        (( ntpindex++ ))
+        (( ntpindex >= ${#ntparray[@]} )) && ntpindex=0 || true
         continue
     fi
     # sometimes the service is down
     if grep -i "is down" <<< "${timediff}" >/dev/null 2>&1
     then
-        (( errorcount++ ))
-        if (( errorcount > MAX_ERROR_COUNT )) && [[ -n "$VERBOSELOGS" ]]
-        then
-            echo "[$(date)][$APPNAME] WARNING: Temporary issue connecting to NTP server ${NTP_REFSERVER} (reported down)"
-            errorcount=0
-        fi
-        sleep $SLEEPTIME
+        echo "[$(date)][$APPNAME] WARNING: Temporary issue connecting to NTP server ${ntparray[$ntpindex]} (reported down); cycling to next NTP server"
+        (( ntpindex++ ))
+        (( ntpindex >= ${#ntparray[@]} )) && ntpindex=0 || true
         continue
     fi
+
     # last check if at least the first field is a digit string
     x="$(awk '{print $1}' <<< "${timediff}")"
     if [ -z "${x##*[!0-9]*}" ]
     then
         echo "${lastchecked},99999,99999,\"Error: ${timediff}\"" > "${RUNFILE}"
-        (( errorcount++ ))
-        if (( errorcount > MAX_ERROR_COUNT )) && [[ -n "$VERBOSELOGS" ]]
-        then
-            echo "[$(date)][$APPNAME] Error: ${timediff}"
-            errorcount=0
-        fi
-        sleep $SLEEPTIME
+        echo "[$(date)][$APPNAME] Error: ${timediff}; cycling to next NTP server"
+        (( ntpindex++ ))
+        (( ntpindex >= ${#ntparray[@]} )) && ntpindex=0 || true
         continue
     fi
 
     # if we are here, then we can print the clockdiff values
     printf "%s000,%s,%s,\"\"\n" "$(awk '{print $1}' <<< "${timediff}")" "$(awk '{print $2}' <<< "${timediff}")" "$(awk '{print $3}' <<< "${timediff}")" > "${RUNFILE}"
-    errorcount=0
     # Be less verbose in logging
     if (( lastlog + LOGINTERVAL < $(date +%s) ))
     then
