more watchdog fun

diff --git a/rootfs/etc/cont-init.d/40-save-recv_host-ip b/rootfs/etc/cont-init.d/40-save-recv_host-ip
--- a/rootfs/etc/cont-init.d/40-save-recv_host-ip
+++ b/rootfs/etc/cont-init.d/40-save-recv_host-ip
@@ -8,6 +8,19 @@
 APPNAME="$(hostname)/40-save-recv_host-ip"
 
 ip_address="$(ping -c1 ${RECV_HOST} | head -1 | awk -F '[()]' '{print $2}')"
+
+if [[ -z "$ip_address" ]]
+then
+  # wait a bit and try again -- the Beast Source container may not yet be up
+  sleep 10
+  ip_address="$(ping -c1 ${RECV_HOST} | head -1 | awk -F '[()]' '{print $2}')"
+  if [[ -z "$ip_address" ]]
+  then
+    echo "[$(date)][${APPNAME}] The IP address for ${RECV_HOST} cannot be resolved. Is your Beast Source system available?"
+    exit 1
+  fi
+fi
+
 echo ${ip_address} > /run/recv_host_ip
 
 echo "[$(date)][${APPNAME}] The IP address for ${RECV_HOST} is ${ip_address}"
