more documentation updates, incl switch to MIT license, init checks and watchdog updates

diff --git a/rootfs/etc/cont-init.d/50-wireguard-setkeys b/rootfs/etc/cont-init.d/50-wireguard-setkeys
--- a/rootfs/etc/cont-init.d/50-wireguard-setkeys
+++ b/rootfs/etc/cont-init.d/50-wireguard-setkeys
@@ -8,7 +8,7 @@ APPNAME="$(hostname)/50-wireguard-setkeys"
 # First we do a few sanity checks:
 
 # put a wg0.conf template in place if needed:
-[[ ! -f /config/wg0.conf ]] && cp /root/wg0.conf /config || true 
+[[ ! -f /config/wg0.conf ]] && cp /root/wg0.conf /config || true
 
 # check if the template has been replaced:
 read -r teststring < /config/wg0.conf
@@ -16,58 +16,72 @@ if [[ "${teststring:0:14}" != "# wg0 template" ]]
 then
   # dont use the template as it has been replaced
   echo "[$APPNAME][$(date)] Using custom uploaded wg0.conf file - ignoring environment variables"
-  exit 0
+  TEMPLATE=false
+else
+  # Check if a bunch of variables are available:
+  EMERGENCY=false
+  TEMPLATE=true
+
+  if [[ "$WG_PRIVKEY" == "" ]]
+  then
+    echo "Emergency!"
+    echo "WG_PRIVKEY must be set. Please update your configuration and restart the container!"
+    EMERGENCY=true
+  fi
+
+  if [[ "$WG_PSK" == "" ]]
+  then
+    echo "Emergency!"
+    echo "WG_PSK must be set. Please update your configuration and restart the container!"
+    EMERGENCY=true
+  fi
+
+  if [[ "$MY_IP" == "" ]]
+  then
+    echo "Emergency!"
+    echo "MY_IP must be set. Please update your configuration and restart the container!"
+    EMERGENCY=true
+  fi
 fi
 
-if [[ "WG_PRIVKEY" == "" ]]
-then
-  echo "Emergency!"
-  echo "WG_PRIVKEY must be set. Please update your configuration and try again!"
-  exit 1
-fi
-
-if [[ "WG_PSK" == "" ]]
-then
-  echo "Emergency!"
-  echo "WG_PSK must be set. Please update your configuration and try again!"
-  exit 1
-fi
-
-if [[ "MY_IP" == "" ]]
-then
-  echo "Emergency!"
-  echo "MY_IP must be set. Please update your configuration and try again!"
-  exit 1
-fi
-
+# Now check if wg0.conf is available and has the necessary elements:
 if [[ ! -f /config/wg0.conf ]]
 then
-  echo "Emergency! \"wg0.conf\" cannot be found. Please contact your container maintainer!"
-  exit 1
+  echo "Emergency! \"wg0.conf\" cannot be found. Please update your configuration and restart the container!"
+  EMERGENCY=true
 fi
 
 if ! grep "PrivateKey =" /config/wg0.conf >/dev/null 2>&1
 then
-  echo "Emergency! PrivateKey variable not found in \"wg0.conf\". Please contact your container maintainer!"
-  exit 1
+  echo "Emergency! PrivateKey variable not found in \"wg0.conf\". Please update your configuration and restart the container!"
+  EMERGENCY=true
 fi
 
 if ! grep "PresharedKey =" /config/wg0.conf >/dev/null 2>&1
 then
-  echo "Emergency! PresharedKey variable not found in \"wg0.conf\". Please contact your container maintainer!"
-  exit 1
+  echo "Emergency! PresharedKey variable not found in \"wg0.conf\". Please update your configuration and restart the container!"
+  EMERGENCY=true
 fi
 
 if ! grep "Address =" /config/wg0.conf >/dev/null 2>&1
 then
-  echo "Emergency! Address variable not found in \"wg0.conf\". Please contact your container maintainer!"
-  exit 1
+  echo "Emergency! Address variable not found in \"wg0.conf\". Please update your configuration and restart the container!"
+  EMERGENCY=true
 fi
 
-# Now we put in the keys in their location:
+if [[ "$EMERGENCY" == "true" ]]
+then
+  # we cannot continue... let's just stop container execution right here
+  sleep infinity
+fi
 
-sed -i 's|\(^\s*PrivateKey\s*=\s*\).*|\1'"$WG_PRIVKEY"'|' /config/wg0.conf
-sed -i 's|\(^\s*PresharedKey\s*=\s*\).*|\1'"$WG_PSK"'|' /config/wg0.conf
-sed -i 's|\(^\s*Address\s*=\s*\).*|\1'"$MY_IP"'|' /config/wg0.conf
+
+# Now we put in the keys in their location, but only if we're using a templated solution:
+if [[ "$TEMPLATE" == "true" ]]
+then
+  sed -i 's|\(^\s*PrivateKey\s*=\s*\).*|\1'"$WG_PRIVKEY"'|' /config/wg0.conf
+  sed -i 's|\(^\s*PresharedKey\s*=\s*\).*|\1'"$WG_PSK"'|' /config/wg0.conf
+  sed -i 's|\(^\s*Address\s*=\s*\).*|\1'"$MY_IP"'|' /config/wg0.conf
+fi
 
 # And done!
diff --git a/rootfs/usr/local/bin/pingbeast b/rootfs/usr/local/bin/pingbeast
--- a/rootfs/usr/local/bin/pingbeast
+++ b/rootfs/usr/local/bin/pingbeast
@@ -2,3 +2,9 @@
 #shellcheck shell=bash
 
 ping -c 5 ${RECV_HOST}
+if [[ $(timeout --preserve-status 5 netcat -z -v ${RECV_HOST} ${RECV_PORT} 2>/dev/null ; echo $?) != "0" ]]
+then
+  echo "We also tried to connect to ${RECV_HOST}:${RECV_PORT}; this failed. Please check that the RECV_HOST and RECV_PORT parameters are set correctly and that your Beast data source is available."
+else
+  echo "We also tried to connect to ${RECV_HOST}:${RECV_PORT}; your Beast Data source appears to be GOOD."
+fi
