update startup procedures to avoid the container getting stuck if readsb isn't functioning (yet)

diff --git a/rootfs/etc/cont-init.d/70-check-beastsource b/rootfs/etc/cont-init.d/70-check-beastsource
--- a/rootfs/etc/cont-init.d/70-check-beastsource
+++ b/rootfs/etc/cont-init.d/70-check-beastsource
@@ -9,11 +9,29 @@ APPNAME="$(hostname)/70-check-beastsource"
 
 rm -f /run/lock/beast-feeder.up
 
+# First see if we can still resolve the ${RECV_HOST}. Reason: if wg0.conf contains DNS settings, then
+# these DNS setting will replace the docker resolution, which means that this container can no longer resolve
+# container names
+
+if [[ "$(timeout --preserve-status 2 ping -c 1 "${RECV_HOST}" >/dev/null 2>&1; echo $?)" == "2" ]]
+then
+  # Exit code 2 for ping means that the domain name couldn't be resolved
+  RECV_HOST="$(cat /run/recv_host_ip)"
+else
+  # we don't need the IP address cache anymore
+  rm -f /run/recv_host_ip
+fi
+
+starttime="$(date +%s)"
+maxwait=60
 while [[ $(timeout --preserve-status 5 netcat -z -v "${RECV_HOST}" "${RECV_PORT}" 2>/dev/null ; echo $?) != "0" ]]
 do
-  echo "[$APPNAME][$(date)] ${RECV_HOST}:${RECV_PORT} is not yet available. Trying again in a bit."
-  sleep 5
+  if (( "$(date +%s)" > starttime + maxwait ))
+  then
+    echo "[$APPNAME][$(date)] ${RECV_HOST}:${RECV_PORT} couldn't be reached for $maxwait seconds. Terminating this container."
+    exit 1
+  else
+    echo "[$APPNAME][$(date)] ${RECV_HOST}:${RECV_PORT} is not yet available; $(("$(date +%s)" - starttime)) of ${maxwait} seconds elapsed. Trying again in a bit."
+    sleep 5
+  fi
 done
-
-#ip_address="$(ping -c1 ${RECV_HOST} | head -1 | awk -F '[()]' '{print $2}')"
-#echo ${ip_address} > /run/recv_host_ip
